[project]
name = "imaging-systems-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy~=2.3",
    "opencv-python==4.10.0.84",
    "pillow~=11.3",
    "pydantic-settings~=2.10",
    "torch~=2.6"
]

[dependency-groups]
dev = [
    "black>=25.1.0",
]
